# Generated by Django 5.0.1 on 2026-02-25 06:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("course_code", models.CharField(max_length=20, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("subject", models.CharField(max_length=100)),
                ("grade_level", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="courses",
                        to="users.teacher",
                    ),
                ),
            ],
            options={
                "db_table": "courses",
            },
        ),
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[
                            ("quiz", "Quiz"),
                            ("assignment", "Assignment"),
                            ("exam", "Exam"),
                            ("essay", "Essay"),
                            ("project", "Project"),
                        ],
                        max_length=20,
                    ),
                ),
                ("total_points", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "passing_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("is_adaptive", models.BooleanField(default=False)),
                (
                    "time_limit",
                    models.IntegerField(
                        blank=True, help_text="Time limit in minutes", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_assessments",
                        to="users.teacher",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="learning.course",
                    ),
                ),
            ],
            options={
                "db_table": "assessments",
            },
        ),
        migrations.CreateModel(
            name="CourseEnrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "enrollment_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("dropped", "Dropped"),
                            ("failed", "Failed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "final_grade",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="learning.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="users.student",
                    ),
                ),
            ],
            options={
                "db_table": "course_enrollments",
            },
        ),
        migrations.CreateModel(
            name="LearningSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("quiz", "Quiz"),
                            ("study", "Study"),
                            ("ai_tutor", "AI Tutor"),
                            ("practice", "Practice"),
                        ],
                        max_length=50,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration",
                    models.IntegerField(
                        blank=True, help_text="Duration in seconds", null=True
                    ),
                ),
                ("questions_attempted", models.IntegerField(default=0)),
                ("questions_correct", models.IntegerField(default=0)),
                ("topics_covered", models.JSONField(blank=True, default=list)),
                ("session_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="learning.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_sessions",
                        to="users.student",
                    ),
                ),
            ],
            options={
                "db_table": "learning_sessions",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice"),
                            ("true_false", "True/False"),
                            ("short_answer", "Short Answer"),
                            ("essay", "Essay"),
                            ("coding", "Coding"),
                        ],
                        max_length=20,
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "question_data",
                    models.JSONField(help_text="Stores options, correct answers, etc."),
                ),
                ("points", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("topic_tags", models.JSONField(blank=True, default=list)),
                ("order_index", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="learning.assessment",
                    ),
                ),
            ],
            options={
                "db_table": "questions",
                "ordering": ["order_index"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("graded", "Graded"),
                            ("in_review", "In Review"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "time_spent",
                    models.IntegerField(
                        blank=True, help_text="Time spent in seconds", null=True
                    ),
                ),
                ("attempt_number", models.IntegerField(default=1)),
                ("ai_graded", models.BooleanField(default=False)),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="learning.assessment",
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graded_submissions",
                        to="users.teacher",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="users.student",
                    ),
                ),
            ],
            options={
                "db_table": "submissions",
            },
        ),
        migrations.CreateModel(
            name="SubmissionAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("answer_data", models.JSONField(help_text="Stores student's answer")),
                ("is_correct", models.BooleanField(blank=True, null=True)),
                (
                    "points_earned",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("ai_feedback", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_answers",
                        to="learning.question",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="learning.submission",
                    ),
                ),
            ],
            options={
                "db_table": "submission_answers",
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("order_index", models.IntegerField()),
                ("prerequisites", models.JSONField(blank=True, default=list)),
                (
                    "estimated_duration",
                    models.IntegerField(
                        blank=True, help_text="Duration in minutes", null=True
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="learning.course",
                    ),
                ),
            ],
            options={
                "db_table": "topics",
                "ordering": ["order_index"],
            },
        ),
        migrations.CreateModel(
            name="StudentSkillProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mastery_level",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Mastery percentage (0-100)",
                        max_digits=4,
                    ),
                ),
                ("attempts_count", models.IntegerField(default=0)),
                ("correct_count", models.IntegerField(default=0)),
                ("last_practiced", models.DateTimeField(blank=True, null=True)),
                (
                    "next_review",
                    models.DateTimeField(
                        blank=True, help_text="For spaced repetition", null=True
                    ),
                ),
                (
                    "difficulty_preference",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "learning_speed",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Questions per hour",
                        max_digits=4,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_profiles",
                        to="learning.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_profiles",
                        to="users.student",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_profiles",
                        to="learning.topic",
                    ),
                ),
            ],
            options={
                "db_table": "student_skill_profiles",
            },
        ),
        migrations.AddField(
            model_name="assessment",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assessments",
                to="learning.topic",
            ),
        ),
        migrations.CreateModel(
            name="AITutorConversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("message_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_conversations",
                        to="users.student",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversations",
                        to="learning.learningsession",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversations",
                        to="learning.topic",
                    ),
                ),
            ],
            options={
                "db_table": "ai_tutor_conversations",
            },
        ),
        migrations.CreateModel(
            name="AITutorMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("ai", "AI"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="learning.aitutorconversation",
                    ),
                ),
            ],
            options={
                "db_table": "ai_tutor_messages",
                "indexes": [
                    models.Index(
                        fields=["conversation"], name="ai_tutor_me_convers_a04b82_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["teacher"], name="courses_teacher_e891c2_idx"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["subject"], name="courses_subject_601605_idx"),
        ),
        migrations.AddIndex(
            model_name="courseenrollment",
            index=models.Index(
                fields=["student"], name="course_enro_student_10a005_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="courseenrollment",
            index=models.Index(
                fields=["course"], name="course_enro_course__4c96ff_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="courseenrollment",
            unique_together={("student", "course")},
        ),
        migrations.AddIndex(
            model_name="learningsession",
            index=models.Index(
                fields=["student"], name="learning_se_student_9a27ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="learningsession",
            index=models.Index(
                fields=["started_at"], name="learning_se_started_f47896_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["assessment"], name="questions_assessm_2b4644_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["difficulty_level"], name="questions_difficu_3585ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["assessment"], name="submissions_assessm_8cd3f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["student"], name="submissions_student_51a963_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["status"], name="submissions_status_dcc854_idx"),
        ),
        migrations.AddIndex(
            model_name="submissionanswer",
            index=models.Index(
                fields=["submission"], name="submission__submiss_eca6df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(fields=["course"], name="topics_course__b0ffaf_idx"),
        ),
        migrations.AddIndex(
            model_name="studentskillprofile",
            index=models.Index(
                fields=["student"], name="student_ski_student_3de830_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentskillprofile",
            index=models.Index(
                fields=["mastery_level"], name="student_ski_mastery_9b0b88_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentskillprofile",
            unique_together={("student", "course", "topic")},
        ),
        migrations.AddIndex(
            model_name="assessment",
            index=models.Index(
                fields=["course"], name="assessments_course__534b36_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assessment",
            index=models.Index(
                fields=["assessment_type"], name="assessments_assessm_603d6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aitutorconversation",
            index=models.Index(
                fields=["student"], name="ai_tutor_co_student_c229d3_idx"
            ),
        ),
    ]
