# Generated by Django 5.0.1 on 2026-02-25 07:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("answer_text", models.TextField(blank=True)),
                ("selected_option", models.CharField(blank=True, max_length=1)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("correct", "Correct"),
                            ("incorrect", "Incorrect"),
                            ("partial", "Partially Correct"),
                        ],
                        default="incorrect",
                        max_length=20,
                    ),
                ),
                (
                    "points_earned",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("ai_feedback", models.TextField(blank=True)),
                ("hints_used", models.IntegerField(default=0)),
                ("time_taken_seconds", models.IntegerField(default=0)),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="learning.question",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_answers",
                        to="users.student",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_answers",
                        to="learning.submission",
                    ),
                ),
            ],
            options={
                "db_table": "student_answers",
                "ordering": ["-answered_at"],
                "indexes": [
                    models.Index(
                        fields=["student"], name="student_ans_student_ab3cd6_idx"
                    ),
                    models.Index(
                        fields=["question"], name="student_ans_questio_0ce8a0_idx"
                    ),
                ],
            },
        ),
    ]
